const dbConfig = require("../config/db.config.js");
const mongoose = require("mongoose");
mongoose.Promise = global.Promise;
const MONGODB_URI = process.env.MONGODB_URI;
const db = {};
db.mongoose = mongoose;
db.url = dbConfig.url;
db.task = require("./task.model.js")(mongoose);
module.exports = db;
